# This starter workflow is for a Ckeepalived project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/ckeepalived-multi-platform.yml
name: build c keepalived linux 2.2.2

on:
  push:
    branches: [ "c/keepalived/linux/2_2_2" ]
  pull_request:
    branches: [ "c/keepalived/linux/2_2_2" ]

env:
  # Customize the Ckeepalived build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The Ckeepalived configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: get_keepalived
      # Configure Ckeepalived in a 'build' subdirectory. `Ckeepalived_BUILD_TYPE` is only required if you are using a single-configuration generator such as keepalived.
      # See https://ckeepalived.org/ckeepalived/help/latest/variable/Ckeepalived_BUILD_TYPE.html?highlight=ckeepalived_build_type
      run: |
        chmod +x ./c/keepalived/linux/2_2_2/get_keepalived.sh
        ./c/keepalived/linux/2_2_2/get_keepalived.sh
