# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build zap linux

on:
  push:
    branches: [ "zig/zap/linux/0_11_0" ]
  pull_request:
    branches: [ "zig/zap/linux/0_11_0" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Zig
      run: |
        wget https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
        sudo tar -xf zig-x86_64-linux-0.15.2.tar.xz -C /usr/local
        echo "/usr/local/zig-x86_64-linux-0.15.2" >> $GITHUB_PATH
        echo 'export PATH="/usr/local/zig-x86_64-linux-0.15.2:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: get_zap_0.11.0
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        chmod +x zip/zap/linux/0.11.0/get_zap_0.11.0.sh
        zip/zap/linux/0.11.0/get_zap_0.11.0.sh
